### ISSUE TITLE
Doesn't properly take into account line breaks

### ISSUE THREAD

**Issue by Traehgniw** [TheWilley/Text2Book#1]
It seems to replace line breaks with a space, which is an issue when you want a line break (e.g. in a recipe book or something).

**Comment by TheWilley** [comment]
I initially did this as a quick and dirty solution as I tried to but failed to handle [escape characters](https://gaming.stackexchange.com/a/384884) , but I could have another go at it.

**Comment by TheWilley** [comment]
Fixed by 4fd1550b1a5eaa090bbb21ed3662c51e060207e0.
