### ISSUE TITLE
website not loading

### ISSUE THREAD

**Issue by BIock64** [TheWilley/Text2Book#16]
so i'm trying to go on the text2book website, but my browser (opera gx) keeps giving me errors, saying the website is inaccessible. is there any reason for this ?

**Comment by TheWilley** [comment]
The website is up and should work fine.
* What kind of errors are you getting? 
* Are you using the correct URL? (https://thewilley.github.io/Text2Book/)?
* Does the same thing happen in other browsers (e.g., edge)?

**Comment by BIock64** [comment]
i am getting an error saying ''website inaccessible, this website took too long to responds''
yes, i am using the right url
it isn't working in google chrome either

**Comment by TheWilley** [comment]
I'm closing this issue as the website indeed is up. I think something may be wrong on your side.
