### ISSUE TITLE
Website not properly generating text to copy

### ISSUE THREAD

**Issue by Traehgniw** [TheWilley/Text2Book#18]
I wrote 12 minecraft book pages of stuff for an SMP I'm on, but only the first page worked properly.

Testing it, each text copy page thing has _all the previous pages_ as well, not just its page! So the last one has the entire book! 

It starts with some text in square brackets, then continues outside the square brackets.

**Comment by TheWilley** [comment]
Good catch! I have no idea how I missed this bug, but I'll make a quick fix.

**Comment by TheWilley** [comment]
Solved by 35a7ad3215b52faeca8d09dc15e7533716f4f3ed. It took a single line of code to fix the problem.
