### ISSUE TITLE
Add support to older versions

### ISSUE THREAD

**Issue by Looxond** [TheWilley/Text2Book#19]
Hello im trying to use the book generator but im on 1.20.1 (java) and the commands that it produces are on 1.21. Is there a way to support older versions?

**Comment by TheWilley** [comment]
The syntax changed during the creation of this project, and I made a commit (ceff37a01abdf575eeff3bd7a7a73549986d5592) to adjust for it. I agree that it would be great to have support for previous versions tho. It would not be too hard either, as we already have a function for formatting:
https://github.com/TheWilley/Text2Book/blob/c318981c26833207cdb51a3a2c435e984904abf5/src/utils/MinecraftBook.ts#L231-L244

We only need to add a parameter for versions, and we're good to go. This issue won't be a priority however, as we need to solve #11 and ideally #10 first

**Comment by TheWilley** [comment]
Solved by b2ddf10931458d7adaa5d2b6407fd5cdd9fb88a2
