### ISSUE TITLE
Strips out quotation marks

### ISSUE THREAD

**Issue by Traehgniw** [TheWilley/Text2Book#2]
The webpage strips out quotation marks and apostrophes (" and ')

**Comment by TheWilley** [comment]
This is intentional. I initially did this as a quick and dirty solution as I tried but failed to handle [escape characters](https://gaming.stackexchange.com/a/384884), but I could have another go at it.

**Comment by TheWilley** [comment]
Fixed by 14478370b199b02725142df93bcbc8c8cb37da2a.

**Comment by Traehgniw** [comment]
Thanks! That was a very quick fix
