### ISSUE TITLE
Square brackets don't work with commands

### ISSUE THREAD

**Issue by Traehgniw** [TheWilley/Text2Book#7]
Due to a strange error where I couldn't log in for no apparent reason an admin friend of mine used text2book's commands function to put some books in the game for me.

However they both started and ended up with square brackets and for some reason these square brackets ended up in the title, instead of in the text. It has also eaten a quotation mark.

I am aware this is very much an edge case

For example, this one is supposed to start with a [

![image](https://github.com/TheWilley/Text2Book/assets/42482668/b04e8678-dc13-4dc0-8eb4-6256d791efe0)

and end with a "] 
![image](https://github.com/TheWilley/Text2Book/assets/42482668/830a714c-7a90-419b-8ae9-481e71c87b7d)

and the title is not supposed to contain [0]
![image](https://github.com/TheWilley/Text2Book/assets/42482668/22f5978e-223c-44ad-a5a1-431e48df3fcd)

**Comment by Traehgniw** [comment]
(closing because it turned out admin friend made a typo and i didn't notice)

**Comment by TheWilley** [comment]
The inclusion of brackets and numbers is automated during command generation, as I believed it would enhance the distinction among generated books with identical titles. Therefore, this behavior is not a bug. However, I realize that users might not prefer the presence of `[n]` in their book titles, and such should be able to exclude it. I have created another issue (#8) to acknowledge the problem.
